name: UrAi CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      FIREBASE_ADMIN_SDK_CONFIG_BASE64: ${{ secrets.FIREBASE_ADMIN_SDK_CONFIG_BASE64 }}

    steps:
      # 1. Check out repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      # 3. Install root dependencies
      - name: Install Dependencies
        run: npm ci

      # 4. Install Firebase Functions dependencies
      - name: Install Firebase Functions Dependencies
        run: cd functions && npm ci

      # 5. Lint code
      - name: Lint Code
        run: npm run lint
        continue-on-error: true

      # 6. Type check
      - name: Type Check
        run: npm run typecheck
        continue-on-error: true

      # 7. Validate AI config
      - name: Validate AI Configuration
        run: npm run ai:validate

      # 8. Unit tests (AI + app logic)
      - name: Run Unit Tests
        run: npm run test:models

      # 9. Build Next.js app
      - name: Build UrAi App
        run: npm run build

      # 10. Install Playwright
      - name: Install Playwright
        run: npx playwright install --with-deps

      # 11. Run end-to-end tests
      - name: Run E2E Tests
        run: npm run test:e2e

      # 12. Firebase secrets check
      - name: Validate Firebase Secrets
        if: github.ref == 'refs/heads/main'
        run: |
          if [ -z "${{ secrets.FIREBASE_TOKEN }}" ]; then
            echo "❌ FIREBASE_TOKEN secret is missing"
            exit 1
          fi
          echo "✅ Firebase token exists"

      # 13. Deploy to Firebase Hosting & Functions
      - name: Deploy to Firebase
        if: github.ref == 'refs/heads/main' && success()
        run: |
          npm install -g firebase-tools
          firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
